CD\
CD C:\Program Files\Williamslea\bin

SC STOP "SYMPHONY INTERLUDE SERVICE"
PAUSE

SC DELETE "SYMPHONY INTERLUDE SERVICE"
PAUSE

REM C:\WINDOWS\MICROSOFT.NET\FRAMEWORK\V4.0.30319\INSTALLUTIL SYMPHONY.INTERLUDE.SERVICE.EXE /u /LogToConsole=true /ShowCallStack
PAUSE

C:\WINDOWS\MICROSOFT.NET\FRAMEWORK\V4.0.30319\INSTALLUTIL SYMPHONY.INTERLUDE.SERVICE.EXE /LogToConsole=true /ShowCallStack
PAUSE

SC FAILURE "SYMPHONY INTERLUDE SERVICE" RESET= 86401 ACTIONS= RESTART/600000
PAUSE

SC START "SYMPHONY INTERLUDE SERVICE"
PAUSE
